### ISSUE TITLE
Clash with Tidyverse googledrive package

### ISSUE THREAD

**Issue by py9mrg** [hairizuanbinnoorazman/rgoogleslides#31]
Hello,

There is a package of the same name `googledrive` by the Tidyverse people, which clashes with your `googledrive` package. I would consider renaming yours, or using theirs instead - which can be done by, for example, changing the lines in your demo from `id <- googledrive::upload_file("first_plot.png")` to `id <- googledrive::drive_upload("first_plot.png")`, and `googledrive::authorize()` to `googledrive::drive_auth()`.

**Comment by muschellij2** [comment]
So you're seeing this.  The `googledrive` from @hairizuanbinnoorazman is last updated in May 2017 (almost 3 years old), so I'd say going back and changing the blog from
https://hairizuan.wordpress.com/2017/05/11/use-case-sending-a-ggplot-graph-into-googleslides/ isn't going to happen, but maybe making an edit to the blog may be possible.

**Comment by hairizuanbinnoorazman** [comment]
Will probably switch to using theirs -> will update the blog posts soon.
The googledrive package by tidyverse didn't exist then; the one that was seen in the blog post is actually a temporary package that I want to release a while later but I guess with tidyverse community taking it up, we can then just rely on theirs.

**Comment by hairizuanbinnoorazman** [comment]
Wordpress site is shut down as blog has been migrated
Refer to the site: https://www.hairizuan.com/sending-ggplot-graphs-to-googleslides/

Information warning added to the top of it

We are unable to use image from Googledrive directly in Googleslides due to changes in Google API
Refer to the issue: https://github.com/hairizuanbinnoorazman/rgoogleslides/issues/28
